/*
 * boot.c - auto-generated by CHDK code_gen2.
 */
#include "lolevel.h"
#include "platform.h"
#include "core.h"

const char * const new_sa = &_end;

extern void handle_jogdial();

void spytask(long ua, long ub, long uc, long ud, long ue, long uf)
{
    (void)ua; (void)ub; (void)uc; (void)ud; (void)ue; (void)uf;
    core_spytask();
}

void CreateTask_spytask()
{
    _CreateTask("SpyTask", 0x19, 0x2000, spytask, 0);
}

void __attribute__((naked,noinline))
debug_logging_my(char* fmt, ...)
{
    (void)fmt;
    asm volatile (
            "    ldr     r0, =mzrm_sendmsg_ret_adr\n"
            "    cmp     r0, lr\n"
            "    beq     chk_msg_type\n"
            "exit_debug_logging_my:\n"
            "    bx      lr\n"

            "chk_msg_type:\n"
            "    ldr     r1, [r11]\n"
            "    cmp     r1, 0x21\n"
            "    beq     do_ui_update\n"
            "    cmp     r1, 0x22\n"
            "    bne     exit_debug_logging_my\n"
            "do_ui_update:\n"
            "    ldr     r0, [r11,0x0c]\n"
            "    b       update_ui\n"
    );
}

void patch_mzrm_sendmsg()
{
    extern int debug_logging_flag;
    extern void (*debug_logging_ptr)(char* fmt, ...);
    debug_logging_flag = 0x200;
    debug_logging_ptr = debug_logging_my;
}

void __attribute__((naked,noinline)) CreateTask_my()
{
    asm volatile (
        "    push   {r0}\n"

        "    ldr     r0, =task_CaptSeq\n"
        "    cmp     r0, r3\n"
        "    itt     eq\n"
        "    ldreq   r3, =capt_seq_task\n"
        "    orreq   r3, #1\n"
        "    beq     exitHook\n"

        "    LDR     R0, =task_ExpDrv\n"
        "    CMP     R0, R3\n"
        "    itt     eq\n"
        "    LDREQ   R3, =exp_drv_task\n"
        "    orreq   r3, #1\n"
        "    BEQ     exitHook\n"

        "    ldr     r0, =task_FileWrite\n"
        "    cmp     r0, r3\n"
        "    itt     eq\n"
        "    ldreq   r3, =filewritetask\n"
        "    orreq   r3, #1\n"
        "    beq     exitHook\n"

        "    ldr     r0, =task_TricInitTask\n"
        "    cmp     r0, r3\n"
        "    itt     eq\n"
        "    ldreq   r3, =task_TricInitTask_my\n"
        "    orreq   r3, #1\n"
        "    BEQ     exitHook\n"

        "    ldr     r0, =task_InitFileModules\n"
        "    cmp     r0, r3\n"
        "    itt     eq\n"
        "    ldreq   r3, =init_file_modules_task\n"
        "    orreq   r3, #1\n"

        "exitHook:\n"
        "    pop    {r0}\n"
        "    stmdb   sp!, {r1, r2, r3, r4, r5, r6, r7, r8, r9, lr}\n"
        "    mov     r4, r0\n"
        "    ldr     r0, =0x0000815c\n"
        "    ldr.w   pc, =(hook_CreateTask + 8 + 1)\n"
        ".ltorg\n"
    );
}

/*
 * ** TEMPORARY? workaround ***
 * Init stuff to avoid asserts on cameras running DryOS r54+
 * https://chdk.setepontos.com/index.php?topic=12516.0
 * Execute this only once
 */
void init_required_fw_features(void)
{
    extern void _init_focus_eventflag();
    extern void _init_nd_eventflag();
    extern int av_override_semaphore;
    extern int _CreateBinarySemaphoreStrictly(int x, int y);
    _init_focus_eventflag();
    _init_nd_eventflag();
    av_override_semaphore = _CreateBinarySemaphoreStrictly(0, 0);
}

/*************************************************************/
//** boot @ 0xFC02000D, length=33 
void __attribute__((naked,noinline)) boot() {
asm volatile (
            "    ldr.w   sp, =0x80010000\n"
            "    bl      sub_fc020064\n"
            "    ldr     r2, =0xc0242010\n"
            "    ldr     r1, [r2]\n"
            "    orr     r1, r1, #1\n"
            "    str     r1, [r2]\n"
            "    ldr     r0, =0xfcd61f00\n"
            "    ldr     r1, =0x010c1000\n"
            "    ldr     r3, =0x010df800\n"
            "loc_fc020024:\n"
            "    cmp     r1, r3\n"
            "    itt     lo\n"
            "    ldrlo   r2, [r0], #4\n"
            "    strlo   r2, [r1], #4\n"
            "    blo     loc_fc020024\n"
            "    ldr     r0, =0x010c1000\n"
            "    ldr     r1, =0x0001e800\n"
            "    bl      sub_fc11b1e2\n" // dcache_clean_range
            "    ldr     r0, =0xfcd34e68\n"
            "    ldr     r1, =0x00008000\n"
            "    ldr     r3, =0x00035098\n"
            "loc_fc020040:\n"
            "    cmp     r1, r3\n"
            "    itt     lo\n"
            "    ldrlo   r2, [r0], #4\n"
            "    strlo   r2, [r1], #4\n"
            "    blo     loc_fc020040\n"
            "    ldr     r3, =0x00035098\n"
            "    ldr     r1, =0x0036c560\n"
            "    mov.w   r2, #0\n"
            "loc_fc020056:\n"
            "    cmp     r3, r1\n"
            "    it      lo\n"
            "    strlo   r2, [r3], #4\n"
            "    blo     loc_fc020056\n"

            // Install CreateTask patch
            "    adr     r0, patch_CreateTask\n" // + Patch data
            "    ldm     r0, {r1,r2}\n"          // + Get two patch instructions
            "    ldr     r0, =hook_CreateTask\n" // + Address to patch, thumb bit is clear in stubs_entry.S
            "    stm     r0, {r1,r2}\n"          // + Store patch instructions

            "    blx     patch_mzrm_sendmsg\n"   // +
            "    b.w     sub_fc062aac_my\n" // Patched (was loc_fc062aac)

            // Data Pool and Payload
            ".align 4\n"                         // + Ensure word alignment for ldm/stm
            "patch_CreateTask:\n"                // +
            "    ldr.w   pc, [pc,#0]\n"          // + Do jump to absolute address CreateTask_my
            "    .long   CreateTask_my + 1\n"    // + has to be a thumb address
            ".ltorg\n"                           // + Dump literals safely
);
}

/*************************************************************/
//** sub_fc062aac_my @ 0xFC062AAD, length=60 
void __attribute__((naked,noinline)) sub_fc062aac_my() {
    // Active Low: 0 means pressed
    if ((*(int*) (0xd20b0000 + 0x98 * 4) & 0x10000) == 0) {
        // WiFi Button -> Access Point Mode
        *(int*) (0x97dc) = 0x100000;
    }
    else if ((*(int*) (0xd20b0000 + 0x97 * 4) & 0x10000) == 0) {
        // Power Button -> Live View Mode
        *(int*) (0x97dc) = 0x200000;
    }
    else {
        // Play Button (or missed timing) -> Playback Mode
        *(int*) (0x97dc) = 0x400000;
    }
asm volatile (
            "    push    {r4, lr}\n"
#if defined(CHDK_NOT_IN_CANON_HEAP)
            "    ldr     r4, =0x0036c560\n"
#else
            "    ldr     r4, =new_sa\n" // +
            "    ldr     r4, [r4]\n"    // +
#endif
            "    sub     sp, #0x78\n"
            "    ldr     r0, =0x006ce000\n"
            "    ldr     r1, =0x0008fd8c\n"
            "    subs    r0, r0, r4\n"
            "    cmp     r0, r1\n"
            "    bhs     loc_fc062abe\n"
            "loc_fc062abc:\n"
            "    b       loc_fc062abc\n"
            "loc_fc062abe:\n"
            "    ldr     r1, =0x00008074\n"
            "    mov.w   r0, #0x80000\n"
            "    str     r0, [r1]\n"
            "    ldr     r1, =0x00008078\n"
            "    ldr     r0, =0x42a21000\n"
            "    str     r0, [r1]\n"
            "    ldr     r1, =0x0000807c\n"
            "    ldr     r0, =0x42a23000\n"
            "    str     r0, [r1]\n"
            "    movs    r1, #0x78\n"
            "    mov     r0, sp\n"
            "    blx     sub_fc2d9764\n" // j_bzero
            "    ldr     r0, =0x0062e000\n"
            "    mov.w   r1, #0xa0000\n"
            "    stm.w   sp, {r0, r1, r4}\n"
            "    ldr     r1, =0x00622274\n" //  *"t"b"
            "    subs    r2, r1, r4\n"
            "    strd    r2, r1, [sp, #0xc]\n"
            "    str     r0, [sp, #0x14]\n"
            "    movs    r0, #0x22\n"
            "    str     r0, [sp, #0x18]\n"
            "    movs    r0, #0x98\n"
            "    str     r0, [sp, #0x1c]\n"
            "    movw    r0, #0x24c\n"
            "    str     r0, [sp, #0x20]\n"
            "    movs    r0, #0xfa\n"
            "    str     r0, [sp, #0x24]\n"
            "    movs    r0, #0xe8\n"
            "    str     r0, [sp, #0x28]\n"
            "    movs    r0, #0x85\n"
            "    str     r0, [sp, #0x2c]\n"
            "    movs    r0, #0x40\n"
            "    str     r0, [sp, #0x30]\n"
            "    movs    r0, #4\n"
            "    str     r0, [sp, #0x34]\n"
            "    movs    r0, #0\n"
            "    str     r0, [sp, #0x38]\n"
            "    movs    r0, #0x10\n"
            "    str     r0, [sp, #0x5c]\n"
            "    movs    r2, #0\n"
            "    lsls    r0, r0, #8\n"
            "    str     r0, [sp, #0x60]\n"
            "    ldr     r1, =sub_fc062c3c_my\n" // Patched (was 0xfc062c3d)
            "    asrs    r0, r0, #4\n"
            "    str     r0, [sp, #0x64]\n"
            "    lsls    r0, r0, #5\n"
            "    str     r0, [sp, #0x68]\n"
            "    mov     r0, sp\n"
            "    blx     sub_fc2d8d9c\n"
            "    add     sp, #0x78\n"
            "    pop     {r4, pc}\n"
);
}

/*************************************************************/
//** sub_fc062c3c_my @ 0xFC062C3D, length=54 
void __attribute__((naked,noinline)) sub_fc062c3c_my() {
asm volatile (
            "    push    {r4, lr}\n"
            "    ldr     r4, =0xfc062ce8\n" //  *"/_term"
            "    bl      sub_fc063f14\n"
            "    ldr     r0, =0x000080ec\n"
            "    ldr     r1, [r0]\n"
            "    ldr     r0, =0x00008074\n"
            "    ldr     r0, [r0]\n"
            "    adds    r0, #0x10\n"
            "    cmp     r1, r0\n"
            "    bhs     loc_fc062c58\n"
            "    ldr     r0, =0xfc062cf8\n" //  *"USER_MEM size checking"
            "    bl      _err_init_task\n"
            "loc_fc062c58:\n"
            "    bl      sub_fc11b2bc\n" // GetSRAndDisableInterrupt
            "    ldr     r3, =0x80000800\n"
            "    mov.w   r1, #0x80000000\n" // capdis bad output (was 0x80000000)
            "    mov.w   r2, #0xeeeeeeee\n" // capdis bad output (was 0xeeeeeeee)
            "loc_fc062c66:\n"
            "    stm     r1!, {r2}\n"
            "    cmp     r1, r3\n"
            "    blo     loc_fc062c66\n"
            "    bl      sub_fc11b2ce\n" // SetSR
            "    bl      sub_fc11b330\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062c7e\n"
            "    ldr     r0, =0xfc062d14\n" //  *"dmSetup"
            "    bl      _err_init_task\n"
            "loc_fc062c7e:\n"
            "    bl      sub_fc0634bc\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062c8c\n"
            "    ldr     r0, =0xfc062d1c\n" //  *"termDriverInit"
            "    bl      _err_init_task\n"
            "loc_fc062c8c:\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc063550\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062c9c\n"
            "    ldr     r0, =0xfc062d2c\n" //  *"termDeviceCreate"
            "    bl      _err_init_task\n"
            "loc_fc062c9c:\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc062e74\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062cac\n"
            "    ldr     r0, =0xfc062d40\n" //  *"stdioSetup"
            "    bl      _err_init_task\n"
            "loc_fc062cac:\n"
            "    bl      sub_fc062fb8\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062cba\n"
            "    ldr     r0, =0xfc062d4c\n" //  *"stdlibSetup"
            "    bl      _err_init_task\n"
            "loc_fc062cba:\n"
            "    bl      sub_fc06633c\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc062cc8\n"
            "    ldr     r0, =0xfc062d58\n" //  *"extlib_setup"
            "    bl      _err_init_task\n"
            "loc_fc062cc8:\n"
            "    pop.w   {r4, lr}\n"
            "    b.w     sub_fc063042_my\n" // Patched (was loc_fc063042)
);
}

/*************************************************************/
//** sub_fc063042_my @ 0xFC063043, length=27 
void __attribute__((naked,noinline)) sub_fc063042_my() {
asm volatile (
            "    push    {r3, lr}\n"
            "    bl      sub_fc06315c\n"
            "    bl      sub_fc0c1c5c\n"
            "    cbnz    r0, loc_fc063058\n"
            "    bl      sub_fc081a46\n" // IsNormalCameraMode_FW
            "    cbz     r0, loc_fc063058\n"
            "    movs    r0, #1\n"
            "    b       loc_fc06305a\n"
            "loc_fc063058:\n"
            "    movs    r0, #0\n"
            "loc_fc06305a:\n"
            "    bl      sub_fc080d38_my\n" // -> power-on mode handling & startupchecks here (was sub_fc080d38)
            "    cbnz    r0, loc_fc063066\n"
            "    bl      sub_fc06314a\n"
            "loc_fc063064:\n"
            "    b       loc_fc063064\n"
            "loc_fc063066:\n"
            "    blx     sub_fc2d8df4\n"
            "    ldr     r1, =0x006ce000\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc3445a8\n" //  return 0
            "    blx     sub_fc2d9314\n"
            "    movs    r3, #0\n"
            "    str     r3, [sp]\n"
            "    ldr     r3, =task_Startup_my\n" //  task_Startup // Patched (was 0xfc062fdd)
            "    movs    r2, #0\n"
            "    movs    r1, #0x19\n"
            "    ldr     r0, =0xfc063094\n" //  *"Startup"
//            "    blx     sub_fc2d9324\n" // j_CreateTask
            "    bl      _CreateTask\n" // Patched
            "    movs    r0, #0\n"
            "    pop     {r3, pc}\n"
);
}

/*************************************************************/
//** sub_fc080d38_my @ 0xFC080D39, length=28 
void __attribute__((naked,noinline)) sub_fc080d38_my() {
asm volatile (
            "    push.w  {r2, r3, r4, r5, r6, r7, r8, lr}\n"
            "    mov     r7, r0\n"
            "    mov.w   r8, #0\n"
            "    bl      sub_fc07461e\n" //  return
            "    movs    r0, #0x97\n"
            "    bl      sub_fc074d7a\n"
            "    movs    r4, #1\n"
            "    bic.w   r5, r4, r0\n"
            "    movs    r0, #0x88\n"
            "    bl      sub_fc074d7a\n"
            "    bic.w   r6, r4, r0\n"
            "    movs    r0, #0x98\n"
            "    bl      sub_fc074d7a\n"
            "    bics    r4, r0\n"
            "    cbz     r7, loc_fc080d6e\n"
            "    orr.w   r0, r5, r6\n"
            "    orrs    r0, r4\n"
            "    beq     loc_fc080d88\n" //  return
            "loc_fc080d6e:\n"
            "    bl      sub_fc0c1c5c\n"
            "    movs    r3, #0\n"
            "    mov     r2, r0\n"
            "    strd    r4, r8, [sp]\n"
            "    mov     r1, r6\n"
            "    mov     r0, r5\n"

            "    ldr     r7, =0x000097dc\n" // +
            "    ldr     r7, [r7]\n"        // + Save our injected default

            "    bl      sub_fc074622\n"
            "    bl      sub_fc074620\n" //  return

            "    ldr     r0, =0x000097dc\n" // +
            "    str     r7, [r0]\n"        // + Put our default right back

            "    movs    r0, #1\n"
            "loc_fc080d88:\n"
            "    pop.w   {r2, r3, r4, r5, r6, r7, r8, pc}\n"
);
}

/*************************************************************/
//** task_Startup_my @ 0xFC062FDD, length=26 
void __attribute__((naked,noinline)) task_Startup_my() {
asm volatile (
            "    push    {r4, lr}\n"
            "    bl      sub_fc0d4f8c\n"
            "    bl      sub_fc063128\n"
//            "    bl      sub_fc0632b4\n" //  return // - nullsub
            "    bl      sub_fc11c688\n"
            // added for SD card UHS detection https://chdk.setepontos.com/index.php?topic=13089.msg132583#msg132583
            "    bl sub_fc0aea96\n" // can be found following SD1stInit create
//            "    bl      sub_fc06330a\n" // - StartDiskboot
            "    bl      sub_fc11c7d6\n"
            "    bl      sub_fc0d5024\n"
            "    bl      sub_fc0633fc\n"
            "    bl      sub_fc06323c\n" // init_ex_drivers
            "    bl      sub_fc11c6c6\n"
            "    bl      sub_fc11c5f0\n" // init_error_handlers
            "    bl      sub_fc0d502a\n"
            "    bl      sub_fc080c2a_my\n" // Patched (was sub_fc080c2a)
            "    bl      CreateTask_spytask\n"         // +
            "    bl      init_required_fw_features\n"  // +
            "    bl      sub_fc27c26a\n"
            "    bl      sub_fc0d5040\n"
            "    bl      sub_fc0d4ce0\n"
            "    bl      sub_fc11c40c\n"
            "    bl      sub_fc0c1b0c\n"
            "    bl      sub_fc0d4eda\n"
            "    bl      sub_fc11c3c8\n"
            "    bl      sub_fc063400\n" //  return
            "    bl      sub_fc30a004\n"
            "    bl      sub_fc11c39c\n"
            "    pop.w   {r4, lr}\n"
            "    b.w     sub_fc0d4f62\n" // jump to FW
);
}

/*************************************************************/
//** sub_fc080c2a_my @ 0xFC080C2B, length=18 
void __attribute__((naked,noinline)) sub_fc080c2a_my() {
asm volatile (
            "    push    {r3, r4, r5, lr}\n"
            "    bl      sub_fc076110\n"
            "    bl      sub_fc0819c4\n" // IsFactoryMode_FW
            "    cbnz    r0, loc_fc080c3a\n"
            "    bl      sub_fc0760b4\n" // OpLog.Start_FW
            "loc_fc080c3a:\n"
            "    ldr     r4, =0x000082c8\n" //  physw_run
            "    ldr     r0, [r4, #4]\n"
            "    cmp     r0, #0\n"
            "    bne     loc_fc080c56\n" //  return
            "    movs    r3, #0\n"
            "    str     r3, [sp]\n"
            "    ldr     r3, =mykbd_task\n" //  task_PhySw // Patched (was 0xfc080c05)
            "    movs    r1, #0x17\n"
            "    ldr     r0, =0xfc080c84\n" //  *"PhySw"
            "    movw    r2, #0x2000\n" // Patched (was 0x800)
            "    blx     sub_fc2d95cc\n" // j_CreateTaskStrictly
            "    str     r0, [r4, #4]\n"
            "loc_fc080c56:\n"
            "    pop     {r3, r4, r5, pc}\n"
);
}

/*************************************************************/
//** init_file_modules_task @ 0xFC0AE2B5, length=16 
void __attribute__((naked,noinline)) init_file_modules_task() {
asm volatile (
            "    push    {r4, r5, r6, lr}\n"
            "    bl      sub_fc0db454\n"
            "    movs    r4, r0\n"
            "    movw    r5, #0x5006\n"
            "    beq     loc_fc0ae2ca\n"
            "    movs    r1, #0\n"
            "    mov     r0, r5\n"
            "    bl      _PostLogicalEventToUI\n"
            "loc_fc0ae2ca:\n"
            "    bl      sub_fc0db47e_my\n" // Patched (was sub_fc0db47e)
            "    bl      core_spytask_can_start\n" // + Set "it's-safe-to-start" flag for spytask
            "    cmp     r4, #0\n"
            "    bne     loc_fc0ae2de\n" //  return
            "    mov     r0, r5\n"
            "    pop.w   {r4, r5, r6, lr}\n"
            "    movs    r1, #0\n"
            "    b.w     _PostLogicalEventToUI\n"
            "loc_fc0ae2de:\n"
            "    pop     {r4, r5, r6, pc}\n"
);
}

/*************************************************************/
//** sub_fc0db47e_my @ 0xFC0DB47F, length=4 jfw
void __attribute__((naked,noinline)) sub_fc0db47e_my() {
asm volatile (
            "    movs    r0, #3\n"
            "    push    {r4, lr}\n"
            "    bl      sub_fc33ddb4_my\n" // Patched (was sub_fc33ddb4)
            "    ldr     pc, =0xfc0db487\n" // Continue in firmware
);
}

/*************************************************************/
//** sub_fc33ddb4_my @ 0xFC33DDB5, length=26 jfw
void __attribute__((naked,noinline)) sub_fc33ddb4_my() {
asm volatile (
            "    push.w  {r4, r5, r6, r7, r8, lr}\n"
            "    mov     r6, r0\n"
            "    bl      sub_fc33dd86\n"
            "    ldr     r1, =0x0003bd68\n"
            "    mov     r5, r0\n"
            "    add.w   r4, r1, r0, lsl #7\n"
            "    ldr     r0, [r4, #0x6c]\n"
            "    lsls    r0, r0, #0x1d\n"
            "    bpl     loc_fc33ddda\n"
            "    movw    r2, #0xa38\n"
            "    ldr     r1, =0xfc33d844\n" //  *"Mounter.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc2d975c\n" // j_DebugAssert
            "loc_fc33ddda:\n"
            "    mov     r1, r6\n"
            "    mov     r0, r5\n"
            "    bl      sub_fc33d6ba\n" // init_sd_io_funcs
            "    ldr     r0, [r4, #0x38]\n"
            "    bl      sub_fc33e2dc\n"
            "    cbnz    r0, loc_fc33ddee\n"
            "    movs    r0, #0\n"
            "    str     r0, [r4, #0x6c]\n"
            "loc_fc33ddee:\n"
            "    mov     r0, r5\n"
            "    bl      sub_fc33d712\n"
            "    mov     r0, r5\n"
            "    bl      sub_fc33d95a_my\n" // Patched (was sub_fc33d95a)
            "    ldr     pc, =0xfc33ddfb\n" // Continue in firmware
);
}

/*************************************************************/
//** sub_fc33d95a_my @ 0xFC33D95B, length=11 jfw
void __attribute__((naked,noinline)) sub_fc33d95a_my() {
asm volatile (
            "    push    {r4, r5, r6, lr}\n"
            "    mov     r5, r0\n"
            "    ldr     r0, =0x0003bd68\n"
            "    add.w   r4, r0, r5, lsl #7\n"
            "    ldr     r0, [r4, #0x6c]\n"
            "    lsls    r0, r0, #0x1e\n"
            "    bmi     sub_fc33d98c\n" //  return 0x1 // jump to FW
            "    ldr     r0, [r4, #0x38]\n"
            "    mov     r1, r5\n"
            "    bl      sub_fc33d770_my\n" // Patched (was sub_fc33d770)
            "    ldr     pc, =0xfc33d973\n" // Continue in firmware
);
}

/*************************************************************/
//** sub_fc33d770_my @ 0xFC33D771, length=107 
void __attribute__((naked,noinline)) sub_fc33d770_my() {
asm volatile (
            "    push.w  {r4, r5, r6, r7, r8, sb, sl, lr}\n"
            "    mov     sl, r0\n"
            "    ldr     r0, =0x0003bd68\n"
            "    mov.w   r8, #0\n"
            "    add.w   r5, r0, r1, lsl #7\n"
            "    mov     r6, r8\n"
            "    mov     sb, r8\n"
            "    ldr     r0, [r5, #0x3c]\n"
            "    cmp     r0, #7\n"
            "    bhs     loc_fc33d872\n"
            "    tbb     [pc, r0]\n" // (jumptable r0 7 elements)
            "branchtable_fc33d78e:\n"
            "    .byte((loc_fc33d7a6 - branchtable_fc33d78e) / 2)\n" // (case 0)
            "    .byte((loc_fc33d796 - branchtable_fc33d78e) / 2)\n" // (case 1)
            "    .byte((loc_fc33d796 - branchtable_fc33d78e) / 2)\n" // (case 2)
            "    .byte((loc_fc33d796 - branchtable_fc33d78e) / 2)\n" // (case 3)
            "    .byte((loc_fc33d796 - branchtable_fc33d78e) / 2)\n" // (case 4)
            "    .byte((loc_fc33d86e - branchtable_fc33d78e) / 2)\n" // (case 5)
            "    .byte((loc_fc33d796 - branchtable_fc33d78e) / 2)\n" // (case 6)
            ".align 1\n"
            "loc_fc33d796:\n"
            "    movs    r2, #0\n"
            "    movw    r1, #0x200\n"
            "    movs    r0, #2\n"
            "    bl      _exmem_ualloc\n"
            "    movs    r4, r0\n"
            "    bne     loc_fc33d7ac\n"
            "loc_fc33d7a6:\n"
            "    movs    r0, #0\n"
            "loc_fc33d7a8:\n"
            "    pop.w   {r4, r5, r6, r7, r8, sb, sl, pc}\n"
            "loc_fc33d7ac:\n"
            "    ldr     r7, [r5, #0x50]\n"
            "    movs    r2, #1\n"
            "    movs    r1, #0\n"
            "    mov     r3, r4\n"
            "    mov     r0, sl\n"
            "    blx     r7\n"
            "    cmp     r0, #1\n"
            "    bne     loc_fc33d7c4\n"
            "    movs    r0, #2\n"
            "    bl      _exmem_ufree\n"
            "    b       loc_fc33d7a6\n" //  return 0
            "loc_fc33d7c4:\n"
            "    ldr     r1, [r5, #0x64]\n"
            "    mov     r0, sl\n"
            "    blx     r1\n"
            "    mov     r1, r4\n"              //  pointer to MBR in r1
            "    bl      mbr_read_dryos\n"      //  total sectors count in r0 before and after call

            // Start of DataGhost's FAT32 autodetection code (Digic6+ version by philmoz)
            // Policy: If there is a partition which has type FAT32 or exFat, use the first one of those for image storage
            // According to the code below, we can use r1, r2, r3 and r12.
            // LR wasn't really used anywhere but for storing a part of the partition signature. This is the only thing
            // that won't work with an offset, but since we can load from LR+offset into LR, we can use this to do that :)
            "    mov     r7, r4\n"              // Copy the MBR start address so we have something to work with
            "    mov     lr, r4\n"              // Save old offset for MBR signature
            "    mov     r1, #1\n"              // Note the current partition number
            "    b       dg_sd_fat32_enter\n"   // We actually need to check the first partition as well, no increments yet!
            "dg_sd_fat32:\n"
            "    cmp     r1, #4\n"              // Did we already see the 4th partition?
            "    beq     dg_sd_fat32_end\n"     // Yes, break. We didn't find anything, so don't change anything.
            "    add     r7, r7, #0x10\n"       // Second partition
            "    add     r1, r1, #1\n"          // Second partition for the loop
            "dg_sd_fat32_enter:\n"
            "    ldrb.w  r2, [r7, #0x1BE]\n"    // Partition status
            "    ldrb.w  r3, [r7, #0x1C2]\n"    // Partition type (FAT32 = 0xB)
            "    cmp     r3, #0xB\n"            // Is this a FAT32 partition?
            "    beq     dg_sd_valid\n"
            "    cmp     r3, #0xC\n"            // Not 0xB, is it 0xC (FAT32 LBA) then?
            "    beq     dg_sd_valid\n"
            "    cmp     r3, #0x7\n"            // exFat?
            "    bne     dg_sd_fat32\n"         // No, it isn't. Loop again.
            "dg_sd_valid:\n"
            "    cmp     r2, #0x00\n"           // It is, check the validity of the partition type
            "    beq     dg_sd_ok\n"
            "    cmp     r2, #0x80\n"
            "    bne     dg_sd_fat32\n"         // Invalid, go to next partition
            "dg_sd_ok:\n"
                                                // This partition is valid, it's the first one, bingo!
            "    mov     r4, r7\n"              // Move the new MBR offset for the partition detection.

            "dg_sd_fat32_end:\n"
            // End of DataGhost's FAT32 autodetection code
            "    ldr.w   r2, [r4, #0x1c7]\n"
            "    mov     r1, r0\n"
            "    ldrb.w  r0, [r4, #0x1c6]\n"
            "    ldr.w   r7, [r4, #0x1cb]\n"
            "    orr.w   r0, r0, r2, lsl #8\n"
            "    ldrb.w  r2, [r4, #0x1ca]\n"
            "    ldrb.w  r3, [r4, #0x1be]\n"
            "    orr.w   r2, r2, r7, lsl #8\n"
//            "    ldrb.w  r7, [r4, #0x1fe]\n" // replaced below
//            "    ldrb.w  r4, [r4, #0x1ff]\n" // replaced below
            "    ldrb.w  r7, [lr, #0x1fe]\n"    // replace instructions above
            "    ldrb.w  r4, [lr, #0x1ff]\n"    // replace instructions above
            "    cbz     r3, loc_fc33d7f6\n"
            "    cmp     r3, #0x80\n"
            "    bne     loc_fc33d808\n"
            "loc_fc33d7f6:\n"
            "    cmp     r1, r0\n"
            "    blo     loc_fc33d808\n"
            "    adds    r3, r0, r2\n"
            "    cmp     r3, r1\n"
            "    bhi     loc_fc33d808\n"
            "    cmp     r7, #0x55\n"
            "    bne     loc_fc33d808\n"
            "    cmp     r4, #0xaa\n"
            "    beq     loc_fc33d850\n"
            "loc_fc33d808:\n"
            "    mov     r4, sb\n"
            "    b       loc_fc33d856\n"
            ".ltorg\n"
            // firmware had literal pool here
            "loc_fc33d850:\n"
            "    movs    r4, #1\n"
            "    mov     r8, r0\n"
            "    mov     r6, r2\n"
            "loc_fc33d856:\n"
            "    movs    r0, #2\n"
            "    bl      _exmem_ufree\n"
            "    cbnz    r4, loc_fc33d880\n"
            "    ldr     r1, [r5, #0x64]\n"
            "    mov.w   r8, #0\n"
            "    mov     r0, sl\n"
            "    blx     r1\n"
            "    mov     r6, r0\n"
            "    b       loc_fc33d880\n"
            "    b       loc_fc33d872\n"
            "loc_fc33d86e:\n"
            "    movs    r6, #0x40\n"
            "    b       loc_fc33d880\n"
            "loc_fc33d872:\n"
            "    movw    r2, #0x651\n"
            "    ldr     r1, =0xfc33d844\n" //  *"Mounter.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc2d975c\n" // j_DebugAssert
            "loc_fc33d880:\n"
            "    strd    r6, sb, [r5, #0x48]\n"
            "    movs    r0, #1\n"
            "    str.w   r8, [r5, #0x44]\n"
            "    b       loc_fc33d7a8\n" //  return
);
}

/*************************************************************/
//** kbd_p2_f_my @ 0xFC0809D1, length=77 
void __attribute__((naked,noinline)) kbd_p2_f_my() {
asm volatile (
            "    push.w  {r4, r5, r6, r7, r8, lr}\n"
            "    ldr     r6, =0x00036990\n"
            "    sub     sp, #0x18\n"
            "    add     r7, sp, #8\n"
            "    subs    r6, #0xc\n"
            "    b       loc_fc080a12\n"
            "loc_fc0809de:\n"
            "    ldr     r1, =0x00036990\n"
            "    add     r3, sp, #8\n"
            "    ldrb.w  r0, [sp, #4]\n"
            "    add     r2, sp, #0x14\n"
            "    subs    r1, #0x18\n"
            "    bl      sub_fc074b80\n"
            "    cbnz    r0, loc_fc0809f8\n"
            "    ldr     r1, [sp, #0x14]\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc080942\n"
            "loc_fc0809f8:\n"
            "    movs    r0, #2\n"
            "loc_fc0809fa:\n"
            "    ldr.w   r1, [r7, r0, lsl #2]\n"
            "    cbz     r1, loc_fc080a0a\n"
            "    ldr.w   r2, [r6, r0, lsl #2]\n"
            "    bics    r2, r1\n"
            "    str.w   r2, [r6, r0, lsl #2]\n"
            "loc_fc080a0a:\n"
            "    subs    r0, r0, #1\n"
            "    sxtb    r0, r0\n"
            "    cmp     r0, #0\n"
            "    bge     loc_fc0809fa\n"
            "loc_fc080a12:\n"
            "    ldr     r0, =0x00036990\n"
            "    add     r1, sp, #4\n"
            "    subs    r0, #0xc\n"
            "    bl      sub_fc0748d2\n"
            "    cmp     r0, #0\n"
            "    bne     loc_fc0809de\n"
            "    ldr.w   r8, =0x00036990\n"
            "    movs    r4, #0\n"
            "loc_fc080a26:\n"
            "    movs    r5, #0\n"
            "    ldr.w   r0, [r6, r4, lsl #2]\n"
            "    ldr.w   r1, [r8, r4, lsl #2]\n"
            "    ands    r0, r1\n"
            "    str.w   r0, [r6, r4, lsl #2]\n"
            "    b       loc_fc080a7e\n"
            "loc_fc080a38:\n"
            "    lsrs    r0, r5\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc080a76\n"
            "    ldr     r1, =0x00036990\n"
            "    add.w   r0, r5, r4, lsl #5\n"
            "    add     r3, sp, #8\n"
            "    subs    r1, #0x18\n"
            "    add     r2, sp, #0x14\n"
            "    uxtb    r0, r0\n"
            "    bl      sub_fc074b80\n"
            "    cbnz    r0, loc_fc080a5a\n"
            "    ldr     r1, [sp, #0x14]\n"
            "    movs    r0, #1\n"
            "    bl      sub_fc080942\n"
            "loc_fc080a5a:\n"
            "    mov     r0, r4\n"
            "    b       loc_fc080a72\n"
            "loc_fc080a5e:\n"
            "    ldr.w   r1, [r7, r0, lsl #2]\n"
            "    cbz     r1, loc_fc080a6e\n"
            "    ldr.w   r2, [r6, r0, lsl #2]\n"
            "    bics    r2, r1\n"
            "    str.w   r2, [r6, r0, lsl #2]\n"
            "loc_fc080a6e:\n"
            "    adds    r0, r0, #1\n"
            "    sxtb    r0, r0\n"
            "loc_fc080a72:\n"
            "    cmp     r0, #3\n"
            "    blt     loc_fc080a5e\n"
            "loc_fc080a76:\n"
            "    ldr.w   r0, [r6, r4, lsl #2]\n"
            "    adds    r5, r5, #1\n"
            "    uxtb    r5, r5\n"
            "loc_fc080a7e:\n"
            "    cmp     r0, #0\n"
            "    bne     loc_fc080a38\n"
            "    adds    r4, r4, #1\n"
            "    sxtb    r4, r4\n"
            "    cmp     r4, #3\n"
            "    blt     loc_fc080a26\n"
            "    bl      sub_fc074720_my\n" // Patched (was sub_fc074720)
            "    add     sp, #0x18\n"
            "    pop.w   {r4, r5, r6, r7, r8, pc}\n"
);
}

/*************************************************************/
//** sub_fc074720_my @ 0xFC074721, length=12 
void __attribute__((naked,noinline)) sub_fc074720_my() {
asm volatile (
            "    push    {r4, lr}\n"
            "    ldr     r4, =0x000097d0\n"
            "    ldr     r0, [r4, #0x18]\n"
            "    bl      sub_fc07725a\n"
            "    ldr     r0, [r4, #0x10]\n"
            "    bl      sub_fc0771d0\n"
            "    bl      sub_fc0772e2\n"
            "    bl      sub_fc0f7d10\n"
            "    ldr     r0, [r4, #0x14]\n"
            "    bl      sub_fc0770ec\n"
            "    bl      handle_jogdial\n" // +
            "    cmp     r0, #0\n"         // +
            "    beq     no_scroll\n"      // +
            "    pop.w   {r4, lr}\n"
            "    b.w     sub_fc072478\n" // jump to FW
            "no_scroll:\n"                 // +
            "    pop     {r4, pc}\n"       // +
            ".ltorg\n"                     // +
);
}

/*************************************************************/
//** task_TricInitTask_my @ 0xFC4EBB3D, length=36 
void __attribute__((naked,noinline)) task_TricInitTask_my() {
asm volatile (
            "    push.w  {r0, r1, r2, r3, r4, r5, r6, r7, r8, sb, sl, fp, ip, lr}\n"
            "    blx     sub_fc2d9624\n" // j_get_self_task_id
            "    movs    r0, #8\n"
            "    ldr     r1, =0xfc4ebd6c\n" //  *"InitTskStart"
            "    bl      sub_fc338156\n"
            "    ldr.w   sl, =0x00027114\n"
            "    movw    fp, #0x1000\n"
            "    ldr     r4, =0x00027110\n"
            "    movs    r2, #0\n"
            "    ldr     r1, =0x0703870f\n"
            "    ldr     r0, [r4]\n"
            "    blx     sub_fc2d971c\n" // j_WaitForAnyEventFlag
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc4ebb76\n"
            "    movs    r0, #8\n"
            "    ldr     r1, =0xfc4ebd84\n" //  *"ER IniTskWait"
            "    bl      sub_fc3381b6\n"
            "    ldr     r1, =0x000270fc\n"
            "    movs    r0, #0\n"
            "    str     r0, [r1]\n"
            "    pop.w   {r0, r1, r2, r3, r4, r5, r6, r7, r8, sb, sl, fp, ip, pc}\n"
            "loc_fc4ebb76:\n"
            "    ldr     r4, =0x00027110\n"
            "    add     r1, sp, #0xc\n"
            "    ldr     r0, [r4]\n"
            "    blx     sub_fc2d95dc\n" // j_GetEventFlagValue
            "    ldr     r1, [sp, #0xc]\n"
            "    ldr     r0, [r4]\n"
            "    blx     sub_fc2d96bc\n" // j_ClearEventFlag
            "    ldr     r0, =0x02000003\n"
            "    ldr     r7, [sp, #0xc]\n"
            "    tst     r7, r0\n"
            "    beq     sub_fc4ebc7a\n" // jump to FW
            "    lsls    r0, r7, #0x1f\n"
            "    beq     sub_fc4ebb9a\n" // jump to FW
            "    ldr     r0, =0xd2020074\n" // +
            "    ldr     r0, [r0]\n"        // + nonzero when core already running
            "    subs    r0, #0\n"          // +
            "    beq     tric1\n"           // +
            "    ldr     r0, [r4]\n"        // + r4 already holds 0x00027110
            "    mov     r1, #0x80\n"       // +
            "    bl      _SetEventFlag\n"   // + core already initialized, set the SmacIdleCmp eventflag here
            "tric1:\n"
            "    bl      sub_fc4ec01e\n"
            "    b       sub_fc4ebc06\n" // jump to FW
);
}
